### ISSUE TITLE
Remember user actions, do not keep reminding for daily updates

### ISSUE THREAD

**Issue by rancidfrog** [whyorean/Galaxy#11]
In update app section the following **turn daily updates on** keeps popping up even after closing it via 'X' button.
![](https://i.imgur.com/aPDQvWU.png)
App should remember setting.
Also, why have reminder when there is already a clear setting in settings:
![](https://i.imgur.com/2nbRIke.png)
?
If user selects Manual, then they do not wish to have any automatic updates whatsoever, nor daily updates as it falls under main category.

**Comment by whyorean** [comment]
Fixed, get the new beta [here](https://github.com/whyorean/Galaxy/releases/tag/v2.0.2-%CE%B2)
