### ISSUE TITLE
How do I change device type

### ISSUE THREAD

**Issue by yakov116** [whyorean/Galaxy#13]
Did your remove this option?

**Comment by anunaym14** [comment]
Swipe up the bottom bar xD

**Comment by yakov116** [comment]
@anunaym14 thanks how in the world would another user figure that out? This is not standard android practice

**Comment by TPS** [comment]
@yakov116 Whaddya say to changing this issue name to reflect the various shenanigans w/ the new UI: "Non-intuitive & missing Settings"?  I still can't locate how to get dark mode back.…

**Comment by anunaym14** [comment]
@yakov116 Yep, you are right and it will be fixed soon
@TPS Dark Mode is not there yet, Iacob is working on it.

**Comment by whyorean** [comment]
Issue resolved, 
Added a seperate section for spoofing
get the new beta [here](https://github.com/whyorean/Galaxy/releases/tag/v2.0.2-%CE%B2)
