### ISSUE TITLE
"Lock" on resuming from background

### ISSUE THREAD

**Issue by 0xlne** [whyorean/Galaxy#17]
Minimizing/sending Aurora to background & then opening it again (for example app link from another app) results in a deadlock.
Aurora needs to be force stopped & restarted, then it will work properly.

Test environment:
Xperia XZ2 on Android 9 DP
Aurora 2.0.1 beta

**Comment by whyorean** [comment]
Fixed, get the new beta [here](https://github.com/whyorean/Galaxy/releases/tag/v2.0.2-%CE%B2)
