### ISSUE TITLE
Crash after start

### ISSUE THREAD

**Issue by matkoyy** [whyorean/Galaxy#19]
Device: Asus MemoPad 8, 581C, Intel x86, Android 5.0
SW version: Aurora Store 2.0.1 β

Application is crashing right after the first loading of the main screen. The first screen to login is OK. Next starts always crash, after cleaning app data, crash workflow is again the same.

**Comment by whyorean** [comment]
Can I get a log ?

**Comment by whyorean** [comment]
@matkoyy 

I really need a log to resolve this issue, meanwhile I closing this.

Potentially Fixed, get the new beta [here](https://github.com/whyorean/Galaxy/releases/tag/v2.0.2-%CE%B2)

**Comment by yakov116** [comment]
Got much worse

**Comment by yakov116** [comment]
@whyorean ?
