### ISSUE TITLE
Apk

### ISSUE THREAD

**Issue by nagayev** [whyorean/Galaxy#2]
Plz add apk file of galaxy project to page of releases

**Comment by anunaym14** [comment]
Hey @nagayev 
To keep a track of releases and beta builds, I request you to join the official telegram group for galaxy i.e t.me/GalaxyOffical . See you there!

**Comment by anunaym14** [comment]
Please copy that link of just search for "GalaxyOfficial" on telegram and you will find it!

**Comment by Lionirdeadman** [comment]
You really shouldn't be required/asked to install and sign up to a service to simply get apks for a project.

Please publish them in releases. At least until Galaxy is in the F-droid repositories.

**Comment by anunaym14** [comment]
@Lionirdeadman Ah..

**Comment by anunaym14** [comment]
@Lionirdeadman It isnt mandatory to join the chat. Its totally optional. Regarding the releases, stable ones are already there on the XDA Thread. Follow that? You don't need to sign up to any service too! Regarding the releases tab and F-droid repository, it will be there once the basic aim of the developer is achieved (that's what he said). BTW it isn't necessary for the developer to post an app on Fdroid, you can too!

**Comment by Lionirdeadman** [comment]
I was simply stating that instead of redirecting him to telegram, you should've simply told him that the developer doesn't wish to put apks in releases until he thinks it's appropriate and that they are available on XDA already.

I didn't mean this to be rude or anything, I simply felt you were ignoring/avoiding his request.

**Comment by anunaym14** [comment]
@Lionirdeadman Sorry if you felt like that, wasn't my intention.

**Comment by nagayev** [comment]
@anunaym14 thanks

**Comment by whyorean** [comment]
Get Galaxy release builds [here](https://github.com/whyorean/Galaxy_Release)

**Comment by Lionirdeadman** [comment]
You really should put the binaries with the [release source code](https://github.com/whyorean/Galaxy/releases) instead of another repository. @whyorean

**Comment by rancidfrog** [comment]
Why not have APK automatically added to release section?
I.E.
- https://github.com/TeamNewPipe/NewPipe/releases
- https://github.com/k9mail/k-9/releases
- https://github.com/yeriomin/YalpStore/releases

Many projects use gradle/Travis for that.
It is better than creating new repo just for releases

**Comment by livingsilver94** [comment]
I agree with the guys above me, having APKs directly in the release section would be much comfortable, and would follow the way Github designed it.

**Comment by yakov116** [comment]
@whyorean  is there a specific reason you dont want the release here?

**Comment by whyorean** [comment]
Okay, you can get the latest binaries on release channel now onwards, I added v1.0.4

**Comment by yakov116** [comment]
@whyorean thank you very much!

Side note: You have the app update via pulling the file from github

**Comment by livingsilver94** [comment]
Waaay cleaner. Thank you!
