### ISSUE TITLE
Progress Bar percentages aren't displayed correctly

### ISSUE THREAD

**Issue by maracuja-juice** [whyorean/Galaxy#4]
This is a UI display bug that I observed (and regularly occurs)

Repro Steps:
- Download an app (it should be at least 90 MB big so that the it needs a long enough time to download)
- Observe the progress bar :)

What I expected to happen:
- The percentages and the progress in the progress bar align. The percentages go from 0 to 100%.

What actually happened:
- The percentages didn't align with the progress bar. And there also negative percentages displayed.

Here are two screenshots from the download screen of some random game application that illustrate the problem: 

Here the percentage isn't aligned with the progress bar. (at 19% the progress bar shouldn't be that much filled...)
![screenshot_20180408-083427](https://user-images.githubusercontent.com/16801528/38466617-6d0d2712-3b2c-11e8-8b3e-cac2ef284d53.png)

And here there are negative percentages displayed:
![screenshot_20180408-083422](https://user-images.githubusercontent.com/16801528/38466618-6d2bc5dc-3b2c-11e8-85ed-e4a3eeb93dde.png)

**Comment by whyorean** [comment]
Acknowledged, will resolve it..

**Comment by whyorean** [comment]
Problem Resolved !

Wait for the latest release build
