### ISSUE TITLE
Reviews crash

### ISSUE THREAD

**Issue by lukechadwick** [whyorean/Galaxy#6]
Found a reproducible crash on reading reviews, doesn't happen on other apps I checked so it might be specific to this one or a few others. 

In galaxy do a search for chromium, go to the Auto Updater for Chromium app, open the reviews, try go to the second page of reviews and it crashes.

**Comment by whyorean** [comment]
Yes it was reported to me, and is fixed.

Wait for the new build, or join the development group on Telegram to have access to latest Alpha.
